spring:
  datasource:
    url: jdbc:mysql://localhost:3306/examination?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  #上传文件配置
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 200MB

# Server settings (ServerProperties)
server:
  port: 8888
  servlet:
    context-path: /examination

log:
  level: INFO
  path: /root/applications/logs/examination-system

cors:
  allowedOrigins: 'http://49.234.19.183'

backupPath: /root/applications/examination.sql